name: 'GitLaw'
description: 'Run GitLaw'
inputs:
  include:
    description: 'repo glob to run action on'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install GitLaw
      run: npm i -g git-law
      shell: bash

    - name: Show info
      run: |
        echo "Include $INCLUDE"
      shell: bash
      env:
        INCLUDE: '${{ inputs.include }}'

    - name: Run GitLaw
      run: git-law remote apply-glob $INCLUDE
      shell: bash
      env:
        INCLUDE: '${{ inputs.include }}'
